<template>
  <div class="text-muted">
    Icono seleccionado: <i v-if="select" :class="select"></i>
    <span v-else>Ninguno</span>
  </div>
  <pre></pre>
  <div
    v-if="!readonly"
    id="picker-container"
    class="row row-cols-6"
    align="center"
  >
    <div
      class="col clickable"
      @click="setValue(icon_class)"
      v-for="(icon_class, i) in icons_classes"
      :key="'icon_class_' + i"
    >
      <div class="card">
        <div class="card-body">
          <i :class="[select == icon_class && 'icon', icon_class]"></i>
        </div>
      </div>
    </div>
  </div>
</template>
<script setup>
import { onMounted, ref } from "vue-demi";

let select = ref("");
const props = defineProps({
  selectedIcon: {
    type: String,
    default: "",
  },
  readonly: {
    type: Boolean,
    default: false,
  },
});
const emit = defineEmits(["onSelectIcon"]);
const setValue = (selected_icon) => {
  if (select.value && select.value == selected_icon) select.value = "";
  else select.value = selected_icon;

  emit("onSelectIcon", select.value);
};
onMounted(() => {
  select.value = props.selectedIcon;
});
const icons_classes = [
  "fa fa-music",
  "fa fa-search",
  "fa fa-heart",
  "fa fa-star",
  "fa fa-user",
  "fa fa-film",
  "fa fa-th-large",
  "fa fa-th",
  "fa fa-th-list",
  "fa fa-check",
  "fa fa-times",
  "fa fa-search-plus",
  "fa fa-search-minus",
  "fa fa-power-off",
  "fa fa-signal",
  "fa fa-cog",
  "fa fa-home",
  "fa fa-road",
  "fa fa-download",
  "fa fa-inbox",
  "fa fa-repeat",
  "fa fa-refresh",
  "fa fa-list-alt",
  "fa fa-lock",
  "fa fa-flag",
  "fa fa-headphones",
  "fa fa-volume-off",
  "fa fa-volume-down",
  "fa fa-volume-up",
  "fa fa-qrcode",
  "fa fa-barcode",
  "fa fa-tag",
  "fa fa-tags",
  "fa fa-book",
  "fa fa-bookmark",
  "fa fa-print",
  "fa fa-camera",
  "fa fa-font",
  "fa fa-bold",
  "fa fa-italic",
  "fa fa-text-height",
  "fa fa-text-width",
  "fa fa-align-left",
  "fa fa-align-center",
  "fa fa-align-right",
  "fa fa-align-justify",
  "fa fa-list",
  "fa fa-outdent",
  "fa fa-indent",
  "fa fa-video-camera",
  "fa fa-pencil",
  "fa fa-map-marker",
  "fa fa-adjust",
  "fa fa-tint",
  "fa fa-arrows",
  "fa fa-step-backward",
  "fa fa-fast-backward",
  "fa fa-backward",
  "fa fa-play",
  "fa fa-pause",
  "fa fa-stop",
  "fa fa-forward",
  "fa fa-fast-forward",
  "fa fa-step-forward",
  "fa fa-eject",
  "fa fa-chevron-left",
  "fa fa-chevron-right",
  "fa fa-plus-circle",
  "fa fa-minus-circle",
  "fa fa-times-circle",
  "fa fa-check-circle",
  "fa fa-question-circle",
  "fa fa-info-circle",
  "fa fa-crosshairs",
  "fa fa-ban",
  "fa fa-arrow-left",
  "fa fa-arrow-right",
  "fa fa-arrow-up",
  "fa fa-arrow-down",
  "fa fa-share",
  "fa fa-expand",
  "fa fa-compress",
  "fa fa-plus",
  "fa fa-minus",
  "fa fa-asterisk",
  "fa fa-exclamation-circle",
  "fa fa-gift",
  "fa fa-leaf",
  "fa fa-fire",
  "fa fa-eye",
  "fa fa-eye-slash",
  "fa fa-exclamation-triangle",
  "fa fa-plane",
  "fa fa-calendar",
  "fa fa-random",
  "fa fa-comment",
  "fa fa-magnet",
  "fa fa-chevron-up",
  "fa fa-chevron-down",
  "fa fa-retweet",
  "fa fa-shopping-cart",
  "fa fa-folder",
  "fa fa-folder-open",
  "fa fa-arrows-v",
  "fa fa-arrows-h",
  "fa fa-bar-chart",
  "fa fa-camera-retro",
  "fa fa-key",
  "fa fa-cogs",
  "fa fa-comments",
  "fa fa-star-half",
  "fa fa-sign-out",
  "fa fa-thumb-tack",
  "fa fa-external-link",
  "fa fa-sign-in",
  "fa fa-trophy",
  "fa fa-upload",
  "fa fa-phone",
  "fa fa-phone-square",
  "fa fa-unlock",
  "fa fa-credit-card",
  "fa fa-rss",
  "fa fa-bullhorn",
  "fa fa-bell",
  "fa fa-certificate",
  "fa fa-arrow-circle-left",
  "fa fa-arrow-circle-right",
  "fa fa-arrow-circle-up",
  "fa fa-arrow-circle-down",
  "fa fa-globe",
  "fa fa-wrench",
  "fa fa-tasks",
  "fa fa-filter",
  "fa fa-briefcase",
  "fa fa-arrows-alt",
  "fa fa-link",
  "fa fa-cloud",
  "fa fa-flask",
  "fa fa-scissors",
  "fa fa-paperclip",
  "fa fa-square",
  "fa fa-bars",
  "fa fa-list-ul",
  "fa fa-list-ol",
  "fa fa-strikethrough",
  "fa fa-underline",
  "fa fa-table",
  "fa fa-magic",
  "fa fa-truck",
  "fa fa-pinterest-square",
  "fa fa-caret-down",
  "fa fa-caret-up",
  "fa fa-caret-left",
  "fa fa-caret-right",
  "fa fa-columns",
  "fa fa-sort",
  "fa fa-sort-desc",
  "fa fa-sort-asc",
  "fa fa-envelope",
  "fa fa-undo",
  "fa fa-gavel",
  "fa fa-tachometer",
  "fa fa-bolt",
  "fa fa-sitemap",
  "fa fa-umbrella",
  "fa fa-clipboard",
  "fa fa-exchange",
  "fa fa-cloud-download",
  "fa fa-cloud-upload",
  "fa fa-user-md",
  "fa fa-stethoscope",
  "fa fa-suitcase",
  "fa fa-coffee",
  "fa fa-cutlery",
  "fa fa-ambulance",
  "fa fa-medkit",
  "fa fa-fighter-jet",
  "fa fa-beer",
  "fa fa-h-square",
  "fa fa-plus-square",
  "fa fa-angle-double-left",
  "fa fa-angle-double-right",
  "fa fa-angle-double-up",
  "fa fa-angle-double-down",
  "fa fa-angle-left",
  "fa fa-angle-right",
  "fa fa-angle-up",
  "fa fa-angle-down",
  "fa fa-desktop",
  "fa fa-laptop",
  "fa fa-tablet",
  "fa fa-mobile",
  "fa fa-quote-left",
  "fa fa-quote-right",
  "fa fa-spinner",
  "fa fa-circle",
  "fa fa-reply",
  "fa fa-gamepad",
  "fa fa-flag-checkered",
  "fa fa-terminal",
  "fa fa-code",
  "fa fa-reply-all",
  "fa fa-location-arrow",
  "fa fa-crop",
  "fa fa-code-fork",
  "fa fa-chain-broken",
  "fa fa-question",
  "fa fa-info",
  "fa fa-exclamation",
  "fa fa-superscript",
  "fa fa-subscript",
  "fa fa-eraser",
  "fa fa-puzzle-piece",
  "fa fa-microphone",
  "fa fa-microphone-slash",
  "fa fa-shield",
  "fa fa-fire-extinguisher",
  "fa fa-rocket",
  "fa fa-chevron-circle-left",
  "fa fa-chevron-circle-right",
  "fa fa-chevron-circle-up",
  "fa fa-chevron-circle-down",
  "fa fa-anchor",
  "fa fa-unlock-alt",
  "fa fa-bullseye",
  "fa fa-ellipsis-h",
  "fa fa-ellipsis-v",
  "fa fa-rss-square",
  "fa fa-play-circle",
  "fa fa-ticket",
  "fa fa-minus-square",
  "fa fa-level-up",
  "fa fa-level-down",
  "fa fa-check-square",
  "fa fa-pencil-square",
  "fa fa-external-link-square",
  "fa fa-share-square",
  "fa fa-compass",
  "fa fa-eur",
  "fa fa-gbp",
  "fa fa-usd",
  "fa fa-inr",
  "fa fa-jpy",
  "fa fa-rub",
  "fa fa-krw",
  "fa fa-btc",
  "fa fa-file",
  "fa fa-file-text",
  "fa fa-sort-alpha-asc",
  "fa fa-sort-alpha-desc",
  "fa fa-sort-amount-asc",
  "fa fa-sort-amount-desc",
  "fa fa-sort-numeric-asc",
  "fa fa-sort-numeric-desc",
  "fa fa-thumbs-up",
  "fa fa-thumbs-down",
  "fa fa-youtube-square",
  "fa fa-instagram",
  "fa fa-flickr",
  "fa fa-adn",
  "fa fa-long-arrow-down",
  "fa fa-long-arrow-up",
  "fa fa-long-arrow-left",
  "fa fa-long-arrow-right",
  "fa fa-female",
  "fa fa-male",
  "fa fa-archive",
  "fa fa-bug",
  "fa fa-pagelines",
  "fa fa-wheelchair",
  "fa fa-try",
  "fa fa-space-shuttle",
  "fa fa-envelope-square",
  "fa fa-university",
  "fa fa-graduation-cap",
  "fa fa-language",
  "fa fa-fax",
  "fa fa-building",
  "fa fa-child",
  "fa fa-paw",
  "fa fa-spoon",
  "fa fa-cube",
  "fa fa-cubes",
  "fa fa-recycle",
  "fa fa-car",
  "fa fa-taxi",
  "fa fa-tree",
  "fa fa-database",
  "fa fa-life-ring",
  "fa fa-paper-plane",
  "fa fa-history",
  "fa fa-header",
  "fa fa-paragraph",
  "fa fa-sliders",
  "fa fa-share-alt",
  "fa fa-share-alt-square",
  "fa fa-bomb",
  "fa fa-tty",
  "fa fa-binoculars",
  "fa fa-plug",
  "fa fa-wifi",
  "fa fa-calculator",
  "fa fa-bell-slash",
  "fa fa-trash",
  "fa fa-copyright",
  "fa fa-at",
  "fa fa-eyedropper",
  "fa fa-paint-brush",
  "fa fa-birthday-cake",
  "fa fa-area-chart",
  "fa fa-pie-chart",
  "fa fa-line-chart",
  "fa fa-toggle-off",
  "fa fa-toggle-on",
  "fa fa-bicycle",
  "fa fa-bus",
  "fa fa-ils",
  "fa fa-cart-plus",
  "fa fa-cart-arrow-down",
  "fa fa-diamond",
  "fa fa-ship",
  "fa fa-user-secret",
  "fa fa-motorcycle",
  "fa fa-street-view",
  "fa fa-heartbeat",
  "fa fa-venus",
  "fa fa-mars",
  "fa fa-mercury",
  "fa fa-transgender",
  "fa fa-transgender-alt",
  "fa fa-venus-double",
  "fa fa-mars-double",
  "fa fa-venus-mars",
  "fa fa-mars-stroke",
  "fa fa-mars-stroke-v",
  "fa fa-mars-stroke-h",
  "fa fa-neuter",
  "fa fa-genderless",
  "fa fa-server",
  "fa fa-user-plus",
  "fa fa-user-times",
  "fa fa-bed",
  "fa fa-viacoin",
  "fa fa-train",
  "fa fa-subway",
  "fa fa-battery-full",
  "fa fa-battery-three-quarters",
  "fa fa-battery-half",
  "fa fa-battery-quarter",
  "fa fa-battery-empty",
  "fa fa-mouse-pointer",
  "fa fa-i-cursor",
  "fa fa-object-group",
  "fa fa-object-ungroup",
  "fa fa-sticky-note",
  "fa fa-sticky-note-o",
  "fa fa-clone",
  "fa fa-balance-scale",
  "fa fa-hourglass-start",
  "fa fa-hourglass-half",
  "fa fa-hourglass-end",
  "fa fa-hourglass",
  "fa fa-trademark",
  "fa fa-registered",
  "fa fa-creative-commons",
  "fa fa-tripadvisor",
  "fa fa-television",
  "fa fa-industry",
  "fa fa-map-pin",
  "fa fa-map-signs",
  "fa fa-map",
  "fa fa-commenting",
  "fa fa-vimeo",
  "fa fa-credit-card-alt",
  "fa fa-pause-circle",
  "fa fa-stop-circle",
  "fa fa-shopping-bag",
  "fa fa-shopping-basket",
  "fa fa-hashtag",
  "fa fa-percent",
  "fa fa-universal-access",
  "fa fa-wheelchair-alt",
  "fa fa-blind",
  "fa fa-audio-description",
  "fa fa-volume-control-phone",
  "fa fa-braille",
  "fa fa-assistive-listening-systems",
  "fa fa-american-sign-language-interpreting",
  "fa fa-deaf",
  "fa fa-sign-language",
  "fa fa-low-vision",
  "fa fa-font-awesome",
  "fa fa-envelope-open",
  "fa fa-address-book",
  "fa fa-address-card",
  "fa fa-user-circle",
  "fa fa-id-badge",
  "fa fa-id-card",
  "fa fa-thermometer-full",
  "fa fa-thermometer-three-quarters",
  "fa fa-thermometer-half",
  "fa fa-thermometer-quarter",
  "fa fa-thermometer-empty",
  "fa fa-shower",
  "fa fa-bath",
  "fa fa-podcast",
  "fa fa-window-maximize",
  "fa fa-window-minimize",
  "fa fa-window-restore",
  "fa fa-window-close",
  "fa fa-microchip",
];
</script>

<style scoped>
#picker-container {
  height: 300px;
  overflow-y: scroll;
}
#picker-container::-webkit-scrollbar {
  display: none; /* Safari and Chrome */
}

.icon {
  color: rgb(90, 193, 116);
}
</style>