import Paginator from "./paginator/Paginator.vue";
import ImagePicker from "./image-pickers/ImagePicker.vue";
import Modal from "./modals/Modal.vue";
import EmptyModal from "./modals/EmptyModal.vue";
import HeaderModal from "./modals/HeaderModal.vue";
import StarsRating from "./rating/StarsRating.vue";
import DotsLoader from "./loaders/DotsLoader.vue";
import Hoping from "./loaders/Hoping.vue";
import SpinnerLoader from "./loaders/SpinnerLoader.vue";
import RippleLoader from "./loaders/RippleLoader.vue";
import Rerender from "./helpers/Rerender.vue";
import CustomSelect from "./helpers/CustomSelect.vue";
import Tab from "./tabs/Tab.vue";
import Avatar from "./avatars/Avatar.vue";
import VideoJs from "./videojs/VideoJs.vue";
import IconPickerSquares from "./pickers/IconPickerSquares.vue";
import SelectPicker from "./pickers/SelectPicker.vue";
import Multiselect from "./pickers/Multiselect.vue";
import Faker from "./randoms/Faker.vue";
import Badge from "./badges/Badge.vue";
import CloseBadge from "./badges/CloseBadge.vue";
import ShowResults from "./empties/ShowResults.vue";
import Forbidden from "./helpers/Forbidden.vue";
import Picture from "./images/Picture.vue";
import LoadingButton from "./buttons/LoadingButton.vue";

export default (app) => {
  app.component("Paginator", Paginator);
  app.component("ImagePicker", ImagePicker);
  app.component("Modal", Modal);
  app.component("EmptyModal", EmptyModal);
  app.component("HeaderModal", HeaderModal);
  app.component("StarsRating", StarsRating);
  app.component("Avatar", Avatar);
  app.component("DotsLoader", DotsLoader);
  app.component("Hoping", Hoping);
  app.component("SpinnerLoader", SpinnerLoader);
  app.component("RippleLoader", RippleLoader);
  app.component("Rerender", Rerender);
  app.component("CustomSelect", CustomSelect);
  app.component("Tab", Tab);
  app.component("VideoJs", VideoJs);
  app.component("Multiselect", Multiselect);
  app.component("SelectPicker", SelectPicker);
  app.component("IconPickerSquares", IconPickerSquares);
  app.component("Faker", Faker);
  app.component("CloseBadge", CloseBadge);
  app.component("Badge", Badge);
  app.component("ShowResults", ShowResults);
  app.component("Forbidden", Forbidden);
  app.component("Picture", Picture);
  app.component("LoadingButton", LoadingButton);
};
